### ISSUE TITLE
Error from Scanner: bufio.Scanner: token too long: Issue when merging

### ISSUE THREAD

**Issue by monksy** [parse-nl/SystemdJournal2Gelf#2]
Recieved another issue when merging:

`Error from Scanner: bufio.Scanner: token too long
`

**Comment by SjonHortensius** [comment]
This is a known issue; I've implemented a fixed max-line-length of 8KiB. I can obviously up this; but I'm not sure what a sane limit is

**Comment by Hr46ph** [comment]
Same issue here.

I found this:
https://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca

Not sure if that helps you. It looks like there might be a ~ 64KiB limit on bufio.scanner and you should use bufio.reader above that?

The problem now is that  a --merge stops and I have no way to know on which line that stops and no way of skipping or continuing and a systemd process crashing whenever this limit is hit.

You could make the max-line-length user configurable through a parameter?

**Comment by SjonHortensius** [comment]
I only see this message maybe once a year, and the systemd service auto-restarts so I never considered this a high-priority issue.

If people bump into it more frequently I will implement this slightly differently, thanks for the links

**Comment by Hr46ph** [comment]
Thanks for the quick reply. Is there a way to skip those lines and continue a merge after this?

**Comment by SjonHortensius** [comment]
Should be fixed in  8b37b7b31f32cd654d1d7bca01b09a5823de2611. If you use the supplied `.service` file the daemon should restart on failure btw

**Comment by Hr46ph** [comment]
Thanks! 👍 

Go build works when I clone from github directly, but on Arch the package doesn't build:

```
~/systemdjournal2gelf $ makepkg -C
==> Making package: systemdjournal2gelf 0.r33.33fb757-1 (Fri 15 Feb 2019 04:34:16 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning systemdjournal2gelf git repo...
Cloning into bare repository '/home/cestmoi/systemdjournal2gelf/systemdjournal2gelf'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 130 (delta 0), reused 3 (delta 0), pack-reused 125
Receiving objects: 100% (130/130), 30.61 KiB | 549.00 KiB/s, done.
Resolving deltas: 100% (70/70), done.
  -> Found systemdjournal2gelf.conf
  -> Found systemdjournal2gelf.service
==> Validating source files with md5sums...
    systemdjournal2gelf ... Skipped
    systemdjournal2gelf.conf ... Passed
    systemdjournal2gelf.service ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of systemdjournal2gelf git repo...
Cloning into 'systemdjournal2gelf'...
done.
==> Starting pkgver()...
==> Updated version: systemdjournal2gelf 0.r39.8b37b7b-1
==> Starting build()...
go: finding github.com/DECK36/go-gelf/gelf latest
go: finding github.com/DECK36/go-gelf latest
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'systemdjournal2gelf': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by SjonHortensius** [comment]
apparently the archlinux package expects a lowercase binary - I guess you should contact @elohmeier - who wrote the PKGBUILD.

**Comment by Hr46ph** [comment]
Sorry I asumed that was yours as well. Anyway, until its fixed, for others running into this, clone the aur package and edit PKGBUILD as follows:
```
# Maintainer: Enno Lohmeier
pkgname=systemdjournal2gelf
binname=SystemdJournal2Gelf
pkgver=0.r39.8b37b7b
pkgrel=1
pkgdesc="Export entries from systemds' journal and send them to a graylog server using gelf"
arch=('any')
url="https://github.com/parse-nl/systemdjournal2gelf"
license=('custom: Simplified BSD')
makedepends=('git' 'go')
source=('git+https://github.com/parse-nl/systemdjournal2gelf.git' 'systemdjournal2gelf.conf' 'systemdjournal2gelf.service')
md5sums=('SKIP'
         'b1d36faab737f215df43167a0fc9d3ff'
         'bad7f3eb935eb50f00e2b63be3b3c6a3')
pkgver() 
{
  cd "$pkgname"
  echo "0.r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
}

build() {
  cd "$pkgname"
  go get github.com/DECK36/go-gelf/gelf
  go build
}

package()
{
  mkdir -p $pkgdir/usr/bin
  mkdir -p $pkgdir/etc
  mkdir -p $pkgdir/etc/systemd/system
 
  install -Dm644 $pkgname.conf "$pkgdir/etc/$pkgname.conf"
  install -Dm644 $pkgname.service "$pkgdir/etc/systemd/system/$pkgname.service"

  cd "$pkgname"
  install -Dm755 "$binname" "$pkgdir/usr/bin/$pkgname"
}

# vim:set ts=2 sw=2 et:
```
Use pacman -U to install it.

And Sjon, thanks again for the quick fix! It's running great so far 😁 !

**Comment by elohmeier** [comment]
@Hr46ph thanks for the fix, I've updated the package!
