### ISSUE TITLE
Add Info for AUR package

### ISSUE THREAD

**Issue by elohmeier** [parse-nl/SystemdJournal2Gelf#3]
FYI, I created an Arch Linux package for your software:
https://aur.archlinux.org/packages/systemdjournal2gelf/

It has a configuration file to set the Gelf-Endpoint-Url and installs the systemd service from your repo.

Maybe you would like to add it to your readme for your users :)

Thanks for your good-working piece of software :)))

**Comment by SjonHortensius** [comment]
Nice; I'll include this in the README if you include the correct license like [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=py3status) for example

**Comment by elohmeier** [comment]
Done!
