### ISSUE TITLE
Graylog additional header

### ISSUE THREAD

**Issue by drzraf** [parse-nl/SystemdJournal2Gelf#7]
OVH hosted Graylog instance (https://www.ovh.com/fr/data-platforms/logs/) works on authentication. The TCP payload must include a specific string `X-OVH-TOKEN: authentication` (could be a header too).

README.md reads `This script supports a special syntax to send additional properties; when you log a JSON encoded object in the Message field it Unmarshalls it for you` but I don't see how to make a use of this to solve above issue.

**Comment by SjonHortensius** [comment]
I don't mind helping you implement this feature - but I need more specific technical documentation. The GELF format uses `gzip` compressed messages over `udp` - there is no notion of a 'header'.

**Comment by drzraf** [comment]
OVH expects JSON object within packets to contains a specific key (`_X-OVH-TOKEN`) whose value is a secret `write token` (an uuid).

**Comment by SjonHortensius** [comment]
So, did you try what happens when you log a message with that token? It might already work fine:
```
$ echo '{"_X-OVH-TOKEN": "TOKEN", "Message": "Test"}' | logger
```

**Comment by drzraf** [comment]
Yes, but only for specific entries instead of all entries selected by `journalctl`.
But I end-up considering logging from PHP instead of systemd itself because of the "one-newline-per-log-entry" limitation of PHP-FPM when logging over syslog.
